import { useEffect, useState } from "react";
import Head from "next/head";
import styles from '../styles/George.module.css'

export default function KudosToGeorge() {
  const [kudos, giveKudos] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      giveKudos(kudo => kudo + 1);
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <Head>
          <title>George loves to bike</title>
          <meta name="description" content="Generated by George for the Kudos" />
          <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22256%22 height=%22256%22 viewBox=%220 0 100 100%22><text x=%2250%%22 y=%2250%%22 dominant-baseline=%22central%22 text-anchor=%22middle%22 font-size=%2290%22>🚴‍♂️</text></svg>" />
      </Head>
      <h1 className={styles.george}>Kudos for George: {kudos}</h1>
    </>
  )
}